### ISSUE TITLE
怎么使用啊

### ISSUE THREAD

**Issue by learningao** [xtyzhen/COC_helper_xtyzhen#1]
怎么使用啊 下载了conda3 cmd里面下载那些代码 找不到指定路径

**Comment by xtyzhen** [comment]
克隆代码（或者下载并解压压缩包），cd进入目录，运行python locate.py 就可以了。
找不到路径可能是cd这一步出错了吧。你可以贴个图。

**Comment by learningao** [comment]
<img width="729" alt="屏幕截图 2021-05-12 111808" src="https://user-images.githubusercontent.com/84055326/117913643-5a432600-b314-11eb-960c-8cc2c1dd972b.png">
成这样就不动了  我小白啥也不会 太麻烦您的话就算了 谢谢了

**Comment by xtyzhen** [comment]
> <img alt="屏幕截图 2021-05-12 111808" width="729" src="https://user-images.githubusercontent.com/84055326/117913643-5a432600-b314-11eb-960c-8cc2c1dd972b.png">
> 
> 成这样就不动了 我小白啥也不会 太麻烦您的话就算了 谢谢了

这样就在运行了，在等待你的COC界面出现。

**Comment by learningao** [comment]
我用模拟器登录就可以使用了是吧 感谢大佬
