### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Jimin111** [xtyzhen/COC_helper_xtyzhen#2]
作者大大你好。运行之后一直循环
*****程序出错，跳过*****
——————————开始运行——————————
怎么处理呢？

**Comment by xtyzhen** [comment]
刚更新了很多内容。可以重新pull后使用，这是迭代多个版本后的结果，目前已稳定运行数月。  
如果依旧有问题请贴出引导出错的界面截图，以及coc版本、代理商信息。

**Comment by Jimin111** [comment]
![image](https://user-images.githubusercontent.com/58162202/128365742-2ca60ce4-ceca-49dc-b0cc-1af5dbe403ec.png)
现在运行locate.py就一直这样

**Comment by xtyzhen** [comment]
试着把main()移动到try上边，和try对齐，观察保存的位置。

**Comment by Jimin111** [comment]
![image](https://user-images.githubusercontent.com/58162202/128372611-09f1730a-5c01-4b9c-af63-b76cbbff4e4b.png)
这是说我没安装opencv吗？

**Comment by xtyzhen** [comment]
pip install opencv-python pyautogui

**Comment by Jimin111** [comment]
![image](https://user-images.githubusercontent.com/58162202/128378526-43bc81e8-00c7-4839-9f7e-4abe9190c5a4.png)
运行起来没报错，但好像也没啥用啊

**Comment by xtyzhen** [comment]
COC呢，要把COC打开，识别到图像才会有所动作。

**Comment by Jimin111** [comment]
打开了的，用的雷电模拟器

**Comment by xtyzhen** [comment]
开的coc是哪家的？保持模拟器窗口大小不变。  有捐兵请求的，才会有反应。
如果依旧无法识别，将文件夹下的图像依次进行重新截图采集。

**Comment by Jimin111** [comment]
coc是google的，窗口大小是720*1280

**Comment by xtyzhen** [comment]
窗口设置为1280*800，重新启动模拟器。

**Comment by Jimin111** [comment]
现在能运行了，但不会根据需要自动造兵

**Comment by xtyzhen** [comment]
兵需要你自己造好，只能做到捐出后自动补充。

**Comment by Jimin111** [comment]
滚木车捐不了呢？

**Comment by xtyzhen** [comment]
由于我自己的账号没有滚木车，你可以用微软官方的截图程序，尝试截图并保存攻城车G5到troops文件夹下，并在locate.py中，开启G5的捐兵选项。
